account/urls.py
from django.urls import path
from .views import user_dashboard, delivery_boy_dashboard, seller_dashboard, user_register, user_login


app_name = "App_Account"

urlpatterns = [
    path('user-register/', user_register, name='user_register'),
    path('user-login', user_login, name='user_login'),
    path('user-dashboard/', user_dashboard, name='user_dashboard'),
    path('delivery-boy-dashboard', delivery_boy_dashboard, name='delivery_boy_dashboard'),
    path('seller-dashboard', seller_dashboard, name='seller_dashboard'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerce.urls')),
    path('account/', include('account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.urls import path
from ecommerce import views

app_name = "App_Ecommerce"

urlpatterns = [
    path('', views.home, name="home"),
    path('category-product', views.category_product_list, name="category_product"),
    path('product-detail-view', views.cart_detail_view, name="product_cart_view"),
    path('single-product-view', views.single_product_view, name="single_product"),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin


# Create your models here.

class MyAccountManager(BaseUserManager):
    def create_user(self, name, username, email, password=None):
        """
        Creates and saves a user with the given name, username, email and password.
        """
        if not username:
            raise ValueError('User must have a username')

        if not email:
            raise ValueError('User must have a valid email')

        user = self.model(
            name=name,
            username=username,
            email=self.normalize_email(email)
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, name, username, email, password=None):
        """
        Creates and saves a superuser with the given name, username, email and password.
        """
        user = self.create_user(
            name=name,
            username=username,
            email=self.normalize_email(email),
            password=password,
        )

        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.superuser = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser, PermissionsMixin):
    name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=255, unique=True)
    phone_number = models.CharField(max_length=50)
    # Required Field
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = MyAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'username']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, add_label):
        return True

category/models.py
from django.db import models
from ckeditor.fields import RichTextField


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name="Category Name")
    slug = models.CharField(max_length=255, unique=True, verbose_name="Category Slug")
    description = RichTextField(blank=True, null=True, verbose_name="Description")
    category_icon = models.ImageField(upload_to="category_icons", blank=True, null=True)
    category_image = models.ImageField(upload_to="category_images", blank=True, null=True, verbose_name="Category Image")
    is_active = models.BooleanField(default=True, verbose_name="Status")
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)

    class Meta:
        ordering = ('name',)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class CategorySection(models.Model):
    category = models.ForeignKey(Category, related_name="category_section", on_delete=models.CASCADE)
    name = models.CharField(max_length=255, verbose_name="Category Section Name")
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)

    class Meta:
        ordering = ('name',)
        verbose_name = "category section"
        verbose_name_plural = "category sections"

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    category = models.ForeignKey(Category, related_name="sub_category", on_delete=models.CASCADE)
    section = models.ForeignKey(CategorySection, related_name="sec_sub_category", on_delete=models.CASCADE)
    name = models.CharField(max_length=255, verbose_name="Subcategory Name")
    slug = models.CharField(max_length=255, unique=True, verbose_name="Subcategory Slug")
    description = RichTextField(blank=True, null=True, verbose_name="Description")
    is_active = models.BooleanField(default=True, verbose_name="status")
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)

    class Meta:
        ordering = ('name',)
        verbose_name = "subcategory"
        verbose_name_plural = "subcategories"

    def __str__(self):
        return self.name

ecommerce/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from .models import Account


class RegistrationFrom(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['name', 'email', 'phone_number', 'password']

account/views.py
from django.shortcuts import render
from .forms import RegistrationFrom


# Create your views here.

def user_register(request):
    form = RegistrationFrom()

    if request.method == 'POST':
        form = RegistrationFrom(request.POST)
        if form.is_valid():
            form.save()

    context = {
        'form': form
    }
    return render(request, 'account/register.html', context)


def user_login(request):
    return render(request, 'account/user_login.html')


def user_dashboard(request):
    return render(request, 'account/user_dashboard.html')


def delivery_boy_dashboard(request):
    return render(request, 'account/dalivery_boy_dashboard.html')


def seller_dashboard(request):
    return render(request, 'account/seller/home.html')

category/views.py
from django.shortcuts import render

# Create your views here.

ecommerce/views.py
from django.shortcuts import render
from category.models import Category

# Create your views here.


def home(request):
    """
    Home page with the product information
    """
    return render(request, 'ecommerce/home.html')


def cart_detail_view(request):
    """
    Load product information with modal when user click add to cart button in home page
    """
    return render(request, 'ecommerce/cart_detail.html')


def category_product_list(request):
    """
    Show all category wise product list with filters options
    """
    return render(request, 'ecommerce/category_product_list.html')


def single_product_view(request):
    """
    Show single product information
    """
    return render(request, 'ecommerce/single_product_view.html')

ecommerce/templates/ecommerce/partials/middle_head.html
<div class="top-navbar bg-white border-bottom border-soft-secondary z-1035 h-35px h-sm-auto">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 col">
                <ul class="list-inline d-flex justify-content-between justify-content-lg-start mb-0">
                    <li class="list-inline-item dropdown mr-3" id="lang-change">
                        <a href="javascript:void(0)" class="dropdown-toggle text-reset py-2" data-toggle="dropdown"
                           data-display="static">
                            <img src="public/assets/img/placeholder.jpg"
                                 data-src="https://demo.activeitzone.com/ecommerce/public/assets/img/flags/en.png"
                                 class="mr-2 lazyload" alt="English" height="11">
                            <span class="opacity-60">English</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-left">
                            <li>
                                <a href="javascript:void(0)" data-flag="en" class="dropdown-item ">
                                    <img src="public/assets/img/placeholder.jpg"
                                         data-src="https://demo.activeitzone.com/ecommerce/public/assets/img/flags/en.png"
                                         class="mr-1 lazyload" alt="English" height="11">
                                    <span class="language">English</span>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0)" data-flag="bd" class="dropdown-item ">
                                    <img src="public/assets/img/placeholder.jpg"
                                         data-src="https://demo.activeitzone.com/ecommerce/public/assets/img/flags/bd.png"
                                         class="mr-1 lazyload" alt="Bangla" height="11">
                                    <span class="language">Bangla</span>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0)" data-flag="sa" class="dropdown-item ">
                                    <img src="public/assets/img/placeholder.jpg"
                                         data-src="https://demo.activeitzone.com/ecommerce/public/assets/img/flags/sa.png"
                                         class="mr-1 lazyload" alt="Arabic" height="11">
                                    <span class="language">Arabic</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="list-inline-item dropdown ml-auto ml-lg-0 mr-0" id="currency-change">
                        <a href="javascript:void(0)" class="dropdown-toggle text-reset py-2 opacity-60"
                           data-toggle="dropdown" data-display="static">
                            U.S. Dollar $
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left">
                            <li>
                                <a class="dropdown-item  active " href="javascript:void(0)" data-currency="USD">U.S.
                                    Dollar ($)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="AUD">Australian
                                    Dollar ($)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="BRL">Brazilian Real
                                    (R$)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="CAD">Canadian Dollar
                                    ($)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="CZK">Czech Koruna
                                    (Kč)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="DKK">Danish Krone
                                    (kr)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="EUR">Euro (€)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="HKD">Hong Kong Dollar
                                    ($)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="HUF">Hungarian Forint
                                    (Ft)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="ILS">Israeli New
                                    Sheqel ()</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="JPY">Japanese Yen
                                    (¥)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="MYR">Malaysian
                                    Ringgit (RM)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="MXN">Mexican Peso
                                    ($)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="NOK">Norwegian Krone
                                    (kr)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="NZD">New Zealand
                                    Dollar ($)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="PHP">Philippine Peso
                                    (₱)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="PLN">Polish Zloty
                                    (zł)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="GBP">Pound Sterling
                                    ()</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="RUB">Russian Ruble
                                    (рб)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="SGD">Singapore Dollar
                                    ($)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="SEK">Swedish Krona
                                    (kr)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="CHF">Swiss Franc
                                    (CHF)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="THB">Thai Baht
                                    (฿)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="BDT">Taka (৳)</a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="javascript:void(0)" data-currency="Rupee">Indian Rupee
                                    (Rs)</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="col-5 text-right d-none d-lg-block">
                <ul class="list-inline mb-0 h-100 d-flex justify-content-end align-items-center">
                    <li class="list-inline-item mr-3 border-right border-left-0 pr-3 pl-0">
                        <a href="tel:+01 112 352 566" class="text-reset d-inline-block opacity-60 py-2">
                            <i class="la la-phone"></i>
                            <span>Help line</span>
                            <span>+01 112 352 566</span>
                        </a>
                    </li>
                    <li class="list-inline-item mr-3 border-right border-left-0 pr-3 pl-0">
                        <a href="{% url 'App_Account:user_login' %}" class="text-reset d-inline-block opacity-60 py-2">Login</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="{% url 'App_Account:user_register' %}"
                           class="text-reset d-inline-block opacity-60 py-2">Registration</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

ecommerce/templates/ecommerce/partials/shop_head.html
{% load static %}
<header class=" sticky-top  z-1020 bg-white border-bottom shadow-sm">
    <div class="position-relative logo-bar-area z-1">
        <div class="container">
            <div class="d-flex align-items-center">

                <div class="col-auto col-xl-3 pl-0 pr-3 d-flex align-items-center">
                    <a class="d-block py-20px mr-3 ml-0" href="{% url 'App_Ecommerce:home' %}">
                        <img src="{% static "public/uploads/all/ikb1MZlSZBdn6Vn0o8JDFrWuVEeuGMBHV6igl9fc.png" %}"
                             alt="Active eCommerce CMS" class="mw-100 h-30px h-md-40px" height="40">
                    </a>

                    <div class="d-none d-xl-block align-self-stretch category-menu-icon-box ml-auto mr-0">
                        <div class="h-100 d-flex align-items-center" id="category-menu-icon">
                            <div class="dropdown-toggle navbar-light bg-light h-40px w-50px pl-2 rounded border c-pointer">
                                <span class="navbar-toggler-icon"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="d-lg-none ml-auto mr-0">
                    <a class="p-2 d-block text-reset" href="javascript:void(0);" data-toggle="class-toggle"
                       data-target=".front-header-search">
                        <i class="las la-search la-flip-horizontal la-2x"></i>
                    </a>
                </div>

                <div class="flex-grow-1 front-header-search d-flex align-items-center bg-white">
                    <div class="position-relative flex-grow-1">
                        <form action="https://demo.activeitzone.com/ecommerce/search" method="GET"
                              class="stop-propagation">
                            <div class="d-flex position-relative align-items-center">
                                <div class="d-lg-none" data-toggle="class-toggle"
                                     data-target=".front-header-search">
                                    <button class="btn px-2" type="button"><i
                                            class="la la-2x la-long-arrow-left"></i></button>
                                </div>
                                <div class="input-group">
                                    <input type="text" class="border-0 border-lg form-control" id="search"
                                           name="keyword" placeholder="I am shopping for..." autocomplete="off">
                                    <div class="input-group-append d-none d-lg-block">
                                        <button class="btn btn-primary" type="submit">
                                            <i class="la la-search la-flip-horizontal fs-18"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <div class="typed-search-box stop-propagation document-click-d-none d-none bg-white rounded shadow-lg position-absolute left-0 top-100 w-100"
                             style="min-height: 200px">
                            <div class="search-preloader absolute-top-center">
                                <div class="dot-loader">
                                    <div></div>
                                    <div></div>
                                    <div></div>
                                </div>
                            </div>
                            <div class="search-nothing d-none p-3 text-center fs-16">

                            </div>
                            <div id="search-content" class="text-left">

                            </div>
                        </div>
                    </div>
                </div>

                <div class="d-none d-lg-none ml-3 mr-0">
                    <div class="nav-search-box">
                        <a href="#" class="nav-box-link">
                            <i class="la la-search la-flip-horizontal d-inline-block nav-box-icon"></i>
                        </a>
                    </div>
                </div>

                <div class="d-none d-lg-block ml-3 mr-0">
                    <div class="" id="compare">
                        <a href="../compare.html" class="d-flex align-items-center text-reset">
                            <i class="la la-refresh la-2x opacity-80"></i>
                            <span class="flex-grow-1 ml-1">
                    <span class="badge badge-primary badge-inline badge-pill">0</span>
                <span class="nav-box-text d-none d-xl-block opacity-70">Compare</span>
    </span>
                        </a></div>
                </div>

                <div class="d-none d-lg-block ml-3 mr-0">
                    <div class="" id="wishlist">
                        <a href="../users/login.html" class="d-flex align-items-center text-reset">
                            <i class="la la-heart-o la-2x opacity-80"></i>
                            <span class="flex-grow-1 ml-1">
                    <span class="badge badge-primary badge-inline badge-pill">0</span>
                <span class="nav-box-text d-none d-xl-block opacity-70">Wishlist</span>
    </span>
                        </a>
                    </div>
                </div>

                <div class="d-none d-lg-block  align-self-stretch ml-3 mr-0" data-hover="dropdown">
                    <div class="nav-cart-box dropdown h-100" id="cart_items">
                        <a href="javascript:void(0)" class="d-flex align-items-center text-reset h-100"
                           data-toggle="dropdown"
                           data-display="static">
                            <i class="la la-shopping-cart la-2x opacity-80"></i>
                            <span class="flex-grow-1 ml-1">
                    <span class="badge badge-primary badge-inline badge-pill cart-count">0</span>
                <span class="nav-box-text d-none d-xl-block opacity-70">Cart</span>
    </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg p-0 stop-propagation">

                            <div class="text-center p-3">
                                <i class="las la-frown la-3x opacity-60 mb-3"></i>
                                <h3 class="h6 fw-700">Your Cart is empty</h3>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="hover-category-menu position-absolute w-100 top-100 left-0 right-0 d-none z-3"
             id="hover-category-menu">
            <div class="container">
                <div class="row gutters-10 position-relative">
                    <div class="col-lg-3 position-static">
                        <div class="aiz-category-menu bg-white rounded  shadow-lg" id="category-sidebar">
                            <div class="p-3 bg-soft-primary d-none d-lg-block rounded-top all-category position-relative text-left">
                                <span class="fw-600 fs-16 mr-3">Categories</span>
                                <a href="../categories.html" class="text-reset">
                                    <span class="d-none d-lg-inline-block">See All ></span>
                                </a>
                            </div>
                            <ul class="list-unstyled categories no-scrollbar py-2 mb-0 text-left">
                                {% for category in categories %}
                                <li class="category-nav-element_back" data-id="{{ category.id }}">
                                    <a href="{% url 'App_Ecommerce:category_product' %}"
                                       class="text-truncate text-reset py-2 px-3 d-block">
                                        <img
                                                class="cat-image lazyload mr-2 opacity-60"
                                                src="{% static "public/assets/img/placeholder.jpg" %}"
                                                data-src="{{ category.category_icon.url }}"
                                                width="16"
                                                alt="Women Clothing &amp; Fashion"
                                                onerror="this.onerror=null;this.src='{% static "public/assets/img/placeholder.jpg" %}';"
                                        >
                                        <span class="cat-name">{{ category.name }}</span>
                                    </a>
                                    <div class="sub-cat-menu c-scrollbar-light rounded shadow-lg p-4">
                                        <div class="c-preloader text-center absolute-center">
                                            <i class="las la-spinner la-spin la-3x opacity-70"></i>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bg-white border-top border-gray-200 py-1">
        <div class="container">
            <ul class="list-inline mb-0 pl-0 mobile-hor-swipe text-center">
                <li class="list-inline-item mr-0">
                    <a href="../index.html"
                       class="opacity-60 fs-14 px-3 py-2 d-inline-block fw-600 hov-opacity-100 text-reset">
                        Home
                    </a>
                </li>
                <li class="list-inline-item mr-0">
                    <a href="../flash-deals.html"
                       class="opacity-60 fs-14 px-3 py-2 d-inline-block fw-600 hov-opacity-100 text-reset">
                        Flash Sale
                    </a>
                </li>
                <li class="list-inline-item mr-0">
                    <a href="../blog.html"
                       class="opacity-60 fs-14 px-3 py-2 d-inline-block fw-600 hov-opacity-100 text-reset">
                        Blogs
                    </a>
                </li>
                <li class="list-inline-item mr-0">
                    <a href="../brands.html"
                       class="opacity-60 fs-14 px-3 py-2 d-inline-block fw-600 hov-opacity-100 text-reset">
                        All Brands
                    </a>
                </li>
                <li class="list-inline-item mr-0">
                    <a href="../categories.html"
                       class="opacity-60 fs-14 px-3 py-2 d-inline-block fw-600 hov-opacity-100 text-reset">
                        All Categories
                    </a>
                </li>
                <li class="list-inline-item mr-0">
                    <a href="../sellers.html"
                       class="opacity-60 fs-14 px-3 py-2 d-inline-block fw-600 hov-opacity-100 text-reset">
                        All Sellers
                    </a>
                </li>
                <li class="list-inline-item mr-0">
                    <a href="../coupons.html"
                       class="opacity-60 fs-14 px-3 py-2 d-inline-block fw-600 hov-opacity-100 text-reset">
                        Coupons
                    </a>
                </li>
            </ul>
        </div>
    </div>
</header>

ecommerce/templates/ecommerce/partials/top_header.html
{% load static %}
<div class="position-relative top-banner removable-session z-1035 d-none" data-key="top-banner" data-value="removed">
    <a href="#" class="d-block text-reset">
        <img src="{% static "public/uploads/all/9iuA7035EikPi8gg5FSLyg8kcUIAzHs2pLAfuiSF.png" %}"
             class="w-100 mw-100 h-50px h-lg-auto img-fit">
    </a>
    <button class="btn text-white absolute-top-right set-session" data-key="top-banner" data-value="removed"
            data-toggle="remove-parent" data-parent=".top-banner">
        <i class="la la-close la-2x"></i>
    </button>
</div>